export interface Break {
  id: number;
  start: string;
  end: string | null;
  duration: number;
  isAuto: boolean;
}

export interface Session {
  id: number;
  clockIn: string;
  clockOut: string | null;
  breakStart: string | null;
  breakEnd: string | null;
  status: 'active' | 'break' | 'completed';
  totalBreakMinutes: number;
  user?: { id: number; fullName: string };
}

export interface DailyStats {
  workedMinutes: number;
  productiveMinutes: number;
  idleMinutes: number;
  breakMinutes: number;
  overtimeMinutes: number;
  expectedMinutes: number;
  missingMinutes: number;
  extraMinutes: number;
  attendanceStatus: 'completed' | 'underworked' | 'overtime' | 'absent' | 'day_off';
}

export interface WeeklyStats {
  expectedHours: number;
  workedHours: number;
  overtimeHours: number;
  missingHours: number;
  productiveHours: number;
  idleHours: number;
  breakHours: number;
  attendanceRate: number;
  completionRate: number;
}

export interface MonthlyStats {
  expectedHours: number;
  workedHours: number;
  overtimeHours: number;
  missingHours: number;
  averageDailyHours: number;
  attendancePercentage: number;
  productivePercentage: number;
}

export interface SessionResponse {
  status: 'clocked_out' | 'active' | 'break';
  sessionId: number | null;
  clockIn: string | null;
  clockOut: string | null;
  breakStartedAt: string | null;
  totalBreakMinutes: number;
  workedTodayMinutes: number;
  weeklyMinutes: number;
  currentProject: { id: number; name: string } | null;
  agentOnline: boolean;
  dailyStats: DailyStats;
  weeklyStats: WeeklyStats;
}

export interface WeeklyHoursResponse {
  hoursByDay: Record<string, number>;
  days: string[];
}

export interface Project {
  id: number;
  name: string;
  description?: string;
  status: 'planning' | 'active' | 'on_hold' | 'completed' | 'cancelled' | 'archived';
  priority?: 'low' | 'medium' | 'high' | 'critical';
  client?: string;
  expectedStart?: string;
  expectedEnd?: string;
  estimatedHours?: number;
  color?: string;
  manager?: { id: number; fullName: string } | null;
  team?: { id: number; name: string } | null;
  users?: { id: number; fullName: string }[];
  hoursThisWeek?: number;
  hoursTotal?: number;
  isActive?: boolean;
  createdAt: string;
}

export interface ProjectAllocation {
  id: number;
  startTime: string | null;
  endTime?: string | null;
  projectId: number | null;
  projectName: string | null;
  durationMinutes?: number;
}

export interface ProjectTimeEntry {
  id: number;
  startTime: string;
  endTime?: string;
  durationMinutes: number;
  autoGenerated: boolean;
  project?: Project;
  user?: { id: number; fullName: string };
  session?: { id: number };
}

export interface TimeEntry {
  id: number;
  date: string;
  hours: number;
  description?: string;
  project?: Project;
  user?: { id: number; fullName: string };
  createdAt: string;
}

export interface Alert {
  id: number;
  type: string;
  title: string;
  severity: 'info' | 'warning' | 'critical';
  message: string;
  isRead: boolean;
  createdAt: string;
  user?: { id: number; fullName?: string };
  session?: { id: number } | null;
}

export interface OvertimeDeclaration {
  id: number;
  date: string;
  workedMinutes: number;
  expectedMinutes: number;
  overtimeMinutes: number;
  reason?: string;
  notes?: string;
  status: 'detected' | 'submitted' | 'pending' | 'approved' | 'rejected' | 'cancelled';
  justificationSubmittedAt?: string;
  reviewedAt?: string;
  user?: { id: number; fullName: string };
  session?: { id: number; clockIn: string; clockOut: string };
  reviewer?: { id: number; fullName: string } | null;
  createdAt: string;
}

export interface HrStats {
  activeNow: number;
  onBreak: number;
  idleFlagged: number;
  totalHoursToday: number;
}

export interface SessionWithWorked extends Session {
  workedMinutes: number;
  breaks?: Break[];
}

export interface SessionHistoryResponse {
  sessions: SessionWithWorked[];
}

export interface TodayDetailResponse {
  sessions: SessionWithWorked[];
  totalWorkedMinutes: number;
  totalBreakMinutes: number;
}

export interface TeamMember {
  id: number;
  fullName: string;
  email: string;
  role: string;
  status: 'active' | 'break' | 'idle' | 'clocked_out';
  currentProject?: string;
  hoursToday: number;
  hoursThisWeek: number;
  lastActivity?: string;
}

export interface CompanyWorkPolicy {
  id?: number;
  expectedDailyHours: number;
  expectedWeeklyHours: number;
  maximumDailyHours: number;
  maximumWeeklyHours: number;
  minimumBreakMinutes: number;
  autoOvertimeEnabled: boolean;
  overtimeStartsAfterDailyHours: number;
  minimumOvertimeThresholdMinutes: number;
  requireHrApproval: boolean;
  requireJustification: boolean;
  allowClockInOutsideSchedule: boolean;
  allowWeekendWork: boolean;
  workingDays: string[];
  lateToleranceMinutes: number;
  earlyLeaveToleranceMinutes: number;
  maximumContinuousWorkHours: number;
  timezone: string;
}

export interface EmployeeWorkStats {
  userId: number;
  fullName: string;
  email: string;
  dailyStats: DailyStats;
  weeklyStats: WeeklyStats;
  monthlyStats: MonthlyStats;
  attendanceEvaluation: string;
  currentSession: {
    status: string;
    clockIn: string;
    durationMinutes: number;
  } | null;
}

export interface RangeSessionsResponse {
  sessions: SessionWithWorked[];
}

export interface TimelineEvent {
  time: string;
  type: 'clock_in' | 'clock_out' | 'break_start' | 'break_end' | 'auto_break' | 'idle' | 'warning';
  label: string;
  detail?: string;
}

export interface DayDetail {
  date: string;
  label: string;
  dayShort: string;
  sessions: SessionWithWorked[];
  totalWorkedMinutes: number;
  totalBreakMinutes: number;
  expectedMinutes: number;
  overtimeMinutes: number;
  missingMinutes: number;
  attendanceStatus: DailyStats['attendanceStatus'];
}

export interface PolicyResponse {
  policy: CompanyWorkPolicy;
}

export interface EmployeeStatsResponse {
  dailyStats: DailyStats;
  weeklyStats: WeeklyStats;
  monthlyStats: MonthlyStats;
  attendanceEvaluation: string;
  currentSession: {
    status: string;
    clockIn: string;
    durationMinutes: number;
  } | null;
}

export type FilterPreset = 'today' | 'yesterday' | 'last-7-days' | 'last-14-days' | 'last-30-days' | 'this-week' | 'previous-week' | 'this-month' | 'previous-month' | 'custom';

export interface FilterState {
  preset: FilterPreset;
  start: string;
  end: string;
  label: string;
}
