import type { Context } from 'koa';

const ALLOC_UID = 'api::project-time-allocation.project-time-allocation';

export default {
  async myActive(ctx: Context) {
    const userId = ctx.state.user?.id;
    if (!userId) return ctx.unauthorized('Authentication required');

    const alloc = await strapi.db.query(ALLOC_UID).findOne({
      where: {
        user: userId,
        endTime: null,
      },
      populate: ['project'],
      orderBy: { startTime: 'desc' },
    });

    if (!alloc) return ctx.send({ allocation: null });
    return ctx.send({
      allocation: {
        id: alloc.id,
        startTime: alloc.startTime,
        projectId: alloc.project?.id ?? null,
        projectName: alloc.project?.name ?? null,
        durationMinutes: alloc.durationMinutes,
      },
    });
  },

  async switchProject(ctx: Context) {
    const userId = ctx.state.user?.id;
    if (!userId) return ctx.unauthorized('Authentication required');

    const { projectId } = ctx.request.body as { projectId: number };
    if (!projectId) return ctx.badRequest('projectId is required');

    const now = new Date().toISOString();

    // Close any active allocation
    const activeAlloc = await strapi.db.query(ALLOC_UID).findOne({
      where: { user: userId, endTime: null },
    });

    if (activeAlloc) {
      const startMs = new Date(activeAlloc.startTime).getTime();
      const endMs = Date.now();
      const minutes = Math.round((endMs - startMs) / 60000);
      await strapi.db.query(ALLOC_UID).update({
        where: { id: activeAlloc.id },
        data: {
          endTime: now,
          durationMinutes: minutes,
        },
      });
    }

    // Find today's active session
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const session = await strapi.db.query('api::session.session').findOne({
      where: {
        user: userId,
        clockIn: { $gte: today.toISOString() },
        status: { $in: ['active', 'break'] },
      },
      orderBy: { clockIn: 'desc' },
    });

    // Create new allocation
    const alloc = await strapi.db.query(ALLOC_UID).create({
      data: {
        startTime: now,
        user: userId,
        project: projectId,
        session: session?.id ?? null,
        autoGenerated: true,
      },
    });

    const project = await strapi.db.query('api::project.project').findOne({
      where: { id: projectId },
    });

    // Emit allocation update
    const io = (strapi as any).io;
    if (io) {
      io.to(`employee:${userId}`).emit('project:allocation-changed', {
        userId,
        allocationId: alloc.id,
        projectId,
        projectName: project?.name ?? 'Unknown',
        startTime: alloc.startTime,
      });
    }

    return ctx.send({
      allocation: {
        id: alloc.id,
        startTime: alloc.startTime,
        projectId: alloc.project ?? projectId,
        projectName: project?.name ?? 'Unknown',
      },
    });
  },

  async stopProject(ctx: Context) {
    const userId = ctx.state.user?.id;
    if (!userId) return ctx.unauthorized('Authentication required');

    const activeAlloc = await strapi.db.query(ALLOC_UID).findOne({
      where: { user: userId, endTime: null },
    });

    if (!activeAlloc) return ctx.send({ allocation: null });

    const startMs = new Date(activeAlloc.startTime).getTime();
    const minutes = Math.round((Date.now() - startMs) / 60000);

    await strapi.db.query(ALLOC_UID).update({
      where: { id: activeAlloc.id },
      data: {
        endTime: new Date().toISOString(),
        durationMinutes: minutes,
      },
    });

    const io = (strapi as any).io;
    if (io) {
      io.to(`employee:${userId}`).emit('project:allocation-changed', {
        userId,
        allocationId: null,
        projectId: null,
        startTime: null,
      });
    }

    return ctx.send({ allocation: null });
  },

  async myProjectTime(ctx: Context) {
    const userId = ctx.state.user?.id;
    if (!userId) return ctx.unauthorized('Authentication required');

    const { start, end, projectId } = ctx.query as {
      start?: string;
      end?: string;
      projectId?: string;
    };

    const where: any = { user: userId };
    if (projectId) where.project = parseInt(projectId, 10);
    if (start || end) {
      where.startTime = {};
      if (start) where.startTime.$gte = new Date(start as string).toISOString();
      if (end) where.startTime.$lte = new Date(end as string).toISOString();
    }

    const allocations = await strapi.db.query(ALLOC_UID).findMany({
      where,
      orderBy: { startTime: 'desc' },
    });

    return ctx.send({ allocations });
  },
};
